# -*- coding: utf-8 -*-
"""weekend_getaway_ranker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CKsRiWCT3Nz15QqdpPuyLqrm3VExEFDb
"""

import pandas as pd
import numpy as np
from math import radians, cos, sin, asin, sqrt

df = pd.read_csv("/content/Top Indian Places to Visit.csv")
df.head()

df.columns

df = df.drop(columns=['Unnamed: 0'])

df = df.rename(columns={
    'State': 'state',
    'City': 'city',
    'Zone': 'zone',
    'Google review rating': 'rating',
    'Number of google review in lakhs': 'popularity'
})

df[['city', 'state', 'zone', 'rating', 'popularity']].head()

df[['rating', 'popularity']] = df[['rating', 'popularity']].fillna(0)

def distance_score(source, destination):
    if source['city'] == destination['city']:
        return 0
    elif source['state'] == destination['state']:
        return 1
    elif source['zone'] == destination['zone']:
        return 2
    else:
        return 3

def weekend_getaway_ranker(source_city, data, top_n=5):

    source = data[data['city'] == source_city]

    if source.empty:
        return "Source city not found in dataset"

    source = source.iloc[0]

    # Weekend-friendly filtering
    destinations = data[
        (data['city'] != source_city) &
        ((data['state'] == source['state']) | (data['zone'] == source['zone']))
    ].copy()

    destinations['distance_score'] = destinations.apply(
        lambda row: distance_score(source, row), axis=1
    )

    destinations['rating_norm'] = destinations['rating'] / destinations['rating'].max()
    destinations['popularity_norm'] = destinations['popularity'] / destinations['popularity'].max()
    destinations['distance_norm'] = destinations['distance_score'] / destinations['distance_score'].max()

    destinations['final_score'] = (
        0.35 * destinations['rating_norm'] +
        0.30 * destinations['popularity_norm'] +
        0.35 * (1 - destinations['distance_norm'])
    )

    return destinations.sort_values(
        'final_score', ascending=False
    )[['Name', 'city', 'state', 'zone', 'rating', 'popularity', 'final_score']].head(top_n)

weekend_getaway_ranker("Kolkata", df)

cities = ["Kolkata", "Mumbai", "Bangalore"]

for city in cities:
    print(f"\nTop Weekend Getaways from {city}")
    display(weekend_getaway_ranker(city, df))